### ISSUE TITLE
Literally Unplayable

### ISSUE THREAD

**Issue by DrZhivago1** [RimWorld-CCL-Reborn/4M-Mehni-s-Misc-Modifications#14]
https://github.com/RimWorld-CCL-Reborn/4M-Mehni-s-Misc-Modifications/blob/3587f788a2f26bd8de8ae69b8d892986b8d7c5b5/Mehni's%20Misc%20Modifications/Settings.cs#L232

_Commit 7102f9b5e1e7ada2803f101560979debc59415fa_ introduced a heinous error (referenced above) roughly nine months ago. This error causes your mod to be unusable, and actually makes the game RimWorld itself unplayable. It should be correctly spelled "I am a modder FFS". That is singular, not plural. Again, no "s". Please fix so I do not have to reinstall Windows OS.
![Untitled](https://user-images.githubusercontent.com/27305214/56783762-284cde80-67a2-11e9-9e6f-234c468c1550.png)

**Comment by Mehni** [comment]
Thank you very much for the detailed report.

**Comment by Mehni** [comment]
EBWODP:

Good luck with your reinstall.
