### ISSUE TITLE
Please add an open-source license to this repository.

### ISSUE THREAD

**Issue by ZXfkSIE** [RimWorld-CCL-Reborn/4M-Mehni-s-Misc-Modifications#22]
A project without any open-source license will be considered as **proprietary** project.
Thank you very much.

**Comment by Mehni** [comment]
MIT. Go nuts.

[Here's the commit](https://github.com/RimWorld-CCL-Reborn/4M-Mehni-s-Misc-Modifications/commit/623f56851c6ccfa8eb89c995a54cf008902f8750) which makes it official.
